DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
  "ID" BIGINT(20) NOT NULL AUTO_INCREMENT,
  "NAME" VARCHAR(150) DEFAULT NULL,
  "CONTACT_NO" VARCHAR(150) DEFAULT NULL,
  "EMAIL" VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

/*DATA FOR THE TABLE "APP_USER" */

INSERT  INTO APP_USER(ID,NAME,CONTACT_NO,EMAIL) VALUES (1, 'Gurvinder Singh', '+91 9643989377', 'gurvinder.singh@jadeglobal.com');

